/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.ManipuladorConsultas;
import control.ManipuladorMedicos;
import model.Consulta;
import control.ManipuladorPacientes;
import javax.swing.JOptionPane;
import model.Paciente;
import model.Medico;



public class ConsultaBuscarEditar extends javax.swing.JFrame {
    
    ConsultaEditar telaConsultaEditar;
    private Paciente pacienteEncontrado;
    private Consulta consultaEncontrada;
    private Medico medicoEncontrado;  
    public ConsultaBuscarEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btConsultaBuscarEditarBuscar = new javax.swing.JButton();
        btConsultaBuscarEditarLimpar = new javax.swing.JButton();
        textConsultaBuscarEditarCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textConsultaBuscarEditar = new javax.swing.JTextArea();
        btConsultaBuscarEditarVoltar = new javax.swing.JButton();
        btConsultaBuscarEditarConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btConsultaBuscarEditarBuscar.setText("BUSCAR");
        btConsultaBuscarEditarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaBuscarEditarBuscarActionPerformed(evt);
            }
        });

        btConsultaBuscarEditarLimpar.setText("LIMPAR");
        btConsultaBuscarEditarLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaBuscarEditarLimparActionPerformed(evt);
            }
        });

        textConsultaBuscarEditarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConsultaBuscarEditarCPFActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textConsultaBuscarEditarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btConsultaBuscarEditarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btConsultaBuscarEditarLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textConsultaBuscarEditarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultaBuscarEditarBuscar)
                    .addComponent(btConsultaBuscarEditarLimpar))
                .addContainerGap())
        );

        jLabel1.setText("CONSULTA BUSCA PARA EDIÇÃO");

        jLabel2.setText("INFORMAÇÕES DA CONSULTA");

        textConsultaBuscarEditar.setEditable(false);
        textConsultaBuscarEditar.setColumns(20);
        textConsultaBuscarEditar.setRows(5);
        jScrollPane1.setViewportView(textConsultaBuscarEditar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btConsultaBuscarEditarVoltar.setText("VOLTAR");
        btConsultaBuscarEditarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaBuscarEditarVoltarActionPerformed(evt);
            }
        });

        btConsultaBuscarEditarConfirmar.setText("CONFIRMAR");
        btConsultaBuscarEditarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaBuscarEditarConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConsultaBuscarEditarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultaBuscarEditarConfirmar)
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultaBuscarEditarVoltar)
                    .addComponent(btConsultaBuscarEditarConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textConsultaBuscarEditarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConsultaBuscarEditarCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConsultaBuscarEditarCPFActionPerformed

    private void btConsultaBuscarEditarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaBuscarEditarConfirmarActionPerformed
        if(consultaEncontrada!=null){
 
        Paciente paciente = null;
        telaConsultaEditar = new ConsultaEditar(this,consultaEncontrada);
        telaConsultaEditar.setLocationRelativeTo(null);
        telaConsultaEditar.setVisible(true);
        this.setVisible(false);
        limpaCampos();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Consulta não encontrado");
        }
    }//GEN-LAST:event_btConsultaBuscarEditarConfirmarActionPerformed

    private void btConsultaBuscarEditarLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaBuscarEditarLimparActionPerformed
        textConsultaBuscarEditarCPF.setText(""); 
        textConsultaBuscarEditar.setText("");
    }//GEN-LAST:event_btConsultaBuscarEditarLimparActionPerformed

    private void btConsultaBuscarEditarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaBuscarEditarVoltarActionPerformed
        textConsultaBuscarEditarCPF.setText(""); 
        textConsultaBuscarEditar.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_btConsultaBuscarEditarVoltarActionPerformed

    private void btConsultaBuscarEditarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaBuscarEditarBuscarActionPerformed
        Consulta consulta;
        Paciente paciente;
        Medico medico;
        String cpf = textConsultaBuscarEditarCPF.getText();
        
        ManipuladorConsultas manipConsulta = new ManipuladorConsultas();
        ManipuladorPacientes manipPacientes = new ManipuladorPacientes();
        ManipuladorMedicos manipMedicos = new ManipuladorMedicos();
        
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Digite um cpf.",
                    "Busca", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            consulta = manipConsulta.buscaPorCpf(Integer.parseInt(cpf));
            paciente = manipPacientes.buscaPorCpf(Integer.parseInt(cpf));
           

            if (consulta != null ) {
                consultaEncontrada = consulta;
                pacienteEncontrado = paciente;
                medico = manipMedicos.buscaPorCrm(consulta.getCrm());
                medicoEncontrado = medico;
                mostraDados();          
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não encontrado!",
                        "Busca", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btConsultaBuscarEditarBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaBuscarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaBuscarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaBuscarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaBuscarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaBuscarEditar().setVisible(true);
            }
        });
    }
    private void limpaCampos() {
        textConsultaBuscarEditar.setText("");
        textConsultaBuscarEditarCPF.setText("");
        
}  
    private void mostraDados() {        
            textConsultaBuscarEditar.setText("DATA DA CONSULTA: "+ consultaEncontrada.getDataConsulta()+"\n" +
            "HORARIO: "  + consultaEncontrada.getHorario()+ "\n" +
            "PACIENTE: " + pacienteEncontrado.getNome() + "\n" +
            "CPF: "+ consultaEncontrada.getCpf()+ "\n" +
            "MEDICO: " + medicoEncontrado.getNome() + "\n" +        
            "CONVENIO: "+consultaEncontrada.getConvenio());   
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultaBuscarEditarBuscar;
    private javax.swing.JButton btConsultaBuscarEditarConfirmar;
    private javax.swing.JButton btConsultaBuscarEditarLimpar;
    private javax.swing.JButton btConsultaBuscarEditarVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textConsultaBuscarEditar;
    private javax.swing.JTextField textConsultaBuscarEditarCPF;
    // End of variables declaration//GEN-END:variables
}
