package view;

import control.ManipuladorMedicos;
import javax.swing.JOptionPane;
import model.Medico;
import exception.ErroCadastroException;

public class MedicoRemover extends javax.swing.JFrame {

    private Medico medicoEncontrado;
    public MedicoRemover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btRemoverMedicoOK = new javax.swing.JButton();
        btRemoverMedicoLimpar = new javax.swing.JButton();
        textRemoverMedicoCRM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMedicoRemover = new javax.swing.JTextArea();
        btRemoverMedicorVoltar = new javax.swing.JButton();
        btRemoverMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btRemoverMedicoOK.setText("BUSCAR");
        btRemoverMedicoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverMedicoOKActionPerformed(evt);
            }
        });

        btRemoverMedicoLimpar.setText("LIMPAR");
        btRemoverMedicoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverMedicoLimparActionPerformed(evt);
            }
        });

        textRemoverMedicoCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRemoverMedicoCRMActionPerformed(evt);
            }
        });

        jLabel3.setText("CRM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textRemoverMedicoCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btRemoverMedicoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRemoverMedicoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRemoverMedicoCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoverMedicoOK)
                    .addComponent(btRemoverMedicoLimpar))
                .addContainerGap())
        );

        jLabel1.setText("REMOVER MÉDICO");

        jLabel2.setText("INFORMAÇÕES DO MÉDICO");

        textMedicoRemover.setColumns(20);
        textMedicoRemover.setRows(5);
        jScrollPane1.setViewportView(textMedicoRemover);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btRemoverMedicorVoltar.setText("VOLTAR");
        btRemoverMedicorVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverMedicorVoltarActionPerformed(evt);
            }
        });

        btRemoverMedico.setText("REMOVER");
        btRemoverMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(btRemoverMedicorVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRemoverMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemoverMedicorVoltar)
                    .addComponent(btRemoverMedico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textRemoverMedicoCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRemoverMedicoCRMActionPerformed

    }//GEN-LAST:event_textRemoverMedicoCRMActionPerformed

    private void btRemoverMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverMedicoActionPerformed
        try {
            if (medicoEncontrado != null) {
                new ManipuladorMedicos().remove(medicoEncontrado.getCrm(), medicoEncontrado); 
            } else {
                throw new RuntimeException();
            }
            verificaRemoverNovamente();
        } catch (ErroCadastroException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRemoverMedicoActionPerformed

    private void btRemoverMedicorVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverMedicorVoltarActionPerformed
        textRemoverMedicoCRM.setText("");
        textMedicoRemover.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_btRemoverMedicorVoltarActionPerformed

    private void btRemoverMedicoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverMedicoLimparActionPerformed
        textRemoverMedicoCRM.setText("");
        textMedicoRemover.setText("");
    }//GEN-LAST:event_btRemoverMedicoLimparActionPerformed

    private void btRemoverMedicoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverMedicoOKActionPerformed
        Medico medico;
        
        String crm = textRemoverMedicoCRM.getText();
        ManipuladorMedicos manipMedico = new ManipuladorMedicos();
        
        if (crm.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Digite um crm.",
                    "Busca", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            medico = manipMedico.buscaPorCrm(Integer.parseInt(crm));

            if (medico != null ) {
                medicoEncontrado = medico;
                mostraDados();          
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não encontrado!",
                        "Busca", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btRemoverMedicoOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaRemover().setVisible(true);
            }
        });
    }
    private void verificaRemoverNovamente() {
        int respUsuario = JOptionPane.showConfirmDialog(rootPane,
                "Remoção realizada com sucesso! Deseja remover outro "
                + "médico?", "Sucesso!", JOptionPane.YES_NO_OPTION);
        switch (respUsuario) {
            case JOptionPane.YES_OPTION:
                btRemoverMedicoLimpar.doClick();
                break;
            case JOptionPane.NO_OPTION:
                btRemoverMedicorVoltar.doClick();
                break;
            default:
                btRemoverMedicorVoltar.doClick();
                break;
        }
    }
    private void limpaCampos() {
        textRemoverMedicoCRM.setText("");
        textMedicoRemover.setText("");
        
} 
    private void mostraDados() {
    textMedicoRemover.setText("NOME: "+ medicoEncontrado.getNome() +"\n" +
    "CRM: "  + medicoEncontrado.getCrm()+ "\n" +
    "ESPECIALIZAÇÃO: "+ medicoEncontrado.getEspecializacao()+ "\n" +
    "TELEFONE: " + medicoEncontrado.getTelefone()+ "\n");    
       
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemoverMedico;
    private javax.swing.JButton btRemoverMedicoLimpar;
    private javax.swing.JButton btRemoverMedicoOK;
    private javax.swing.JButton btRemoverMedicorVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textMedicoRemover;
    private javax.swing.JTextField textRemoverMedicoCRM;
    // End of variables declaration//GEN-END:variables
}
