/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.*;
import control.ManipuladorPacientes;
import exception.ErroCadastroException;
import exception.ValorInvalidoException;
import model.Paciente;
import javax.swing.JOptionPane;


/**
 *
 * @author Mateus
 */
public class PacienteEditar extends javax.swing.JFrame {
    
    PacienteBuscarEditar telaPacienteBuscarEditar;
    private final Paciente pacienteEdit;
   
    
    public PacienteEditar(PacienteBuscarEditar telaPacienteBuscarEditar, Paciente pacienteEdit) {
        initComponents();
        
        this.telaPacienteBuscarEditar = telaPacienteBuscarEditar;
        this.pacienteEdit = pacienteEdit;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btConsultaAdicionarVoltar = new javax.swing.JButton();
        textPacienteEditarCPF = new javax.swing.JTextField();
        textPacienteEditarEndereco = new javax.swing.JTextField();
        textPacienteEditarTelefone = new javax.swing.JTextField();
        textPacienteEditarNome = new javax.swing.JTextField();
        textPacienteEditarNascimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btPacienteEditarVoltar = new javax.swing.JButton();
        btPacienteEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        btConsultaAdicionarVoltar.setText("VOLTAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textPacienteEditarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteEditarCPFActionPerformed(evt);
            }
        });

        textPacienteEditarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteEditarEnderecoActionPerformed(evt);
            }
        });

        textPacienteEditarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteEditarTelefoneActionPerformed(evt);
            }
        });

        textPacienteEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteEditarNomeActionPerformed(evt);
            }
        });

        textPacienteEditarNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteEditarNascimentoActionPerformed(evt);
            }
        });

        jLabel1.setText("PACIENTE");

        btPacienteEditarVoltar.setText("VOLTAR");
        btPacienteEditarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacienteEditarVoltarActionPerformed(evt);
            }
        });

        btPacienteEditar.setText("EDITAR");
        btPacienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacienteEditarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Nascimento");

        jLabel4.setText("CPF");

        jLabel5.setText("Endereço");

        jLabel6.setText("Telefone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btPacienteEditarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btPacienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textPacienteEditarNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textPacienteEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textPacienteEditarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textPacienteEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textPacienteEditarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPacienteEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPacienteEditarNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPacienteEditarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPacienteEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPacienteEditarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPacienteEditarVoltar)
                    .addComponent(btPacienteEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPacienteEditarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteEditarCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteEditarCPFActionPerformed

    private void textPacienteEditarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteEditarEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteEditarEnderecoActionPerformed

    private void textPacienteEditarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteEditarTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteEditarTelefoneActionPerformed

    private void textPacienteEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteEditarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteEditarNomeActionPerformed

    private void textPacienteEditarNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteEditarNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteEditarNascimentoActionPerformed

    private void btPacienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacienteEditarActionPerformed
        if (passouNaPreValidacao()) {
            try {
                editaPaciente();
                JOptionPane.showMessageDialog(rootPane, "Alterações salvas "
                        + "com sucesso!", "Edição",
                        JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                dispose();
            } catch (ValorInvalidoException | ErroCadastroException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        
        this.setVisible(false); 
    }//GEN-LAST:event_btPacienteEditarActionPerformed

    private void btPacienteEditarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacienteEditarVoltarActionPerformed
        this.setVisible(false); 
        limpaCampos();
        telaPacienteBuscarEditar.setLocationRelativeTo(null);
        telaPacienteBuscarEditar.setVisible(true);
    }//GEN-LAST:event_btPacienteEditarVoltarActionPerformed

    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteEditar(new PacienteBuscarEditar(), new Paciente()).setVisible(true);
            }
        });
    }
    private boolean passouNaPreValidacao() {
        String nome = textPacienteEditarNome.getText();
        String telefone = textPacienteEditarTelefone.getText();
        String dataNascimento = textPacienteEditarNascimento.getText();
        String cpf = textPacienteEditarCPF.getText();
        String endereco = textPacienteEditarTelefone.getText();

        if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty()|| dataNascimento.isEmpty() || endereco.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem todos os campos foram "
                    + "preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    private void editaPaciente() throws ValorInvalidoException, ErroCadastroException {
        String nome = textPacienteEditarNome.getText();
        String telefone = textPacienteEditarTelefone.getText();
        String dataNascimento =textPacienteEditarNascimento.getText();
        String cpf = textPacienteEditarCPF.getText();
        String endereco = textPacienteEditarEndereco.getText();
           
        Paciente pacienteE = new Paciente();
       
        pacienteE.setNome(nome);
        pacienteE.setTelefone(Integer.parseInt(telefone));
        pacienteE.setNascimento(dataNascimento);
        pacienteE.setCpf(Integer.parseInt(cpf));
        pacienteE.setEndereco(endereco);
        new ManipuladorPacientes().edita(pacienteEdit.getCpf(), pacienteE);
    }

    private void limpaCampos() {
        textPacienteEditarNome.setText("");
        textPacienteEditarTelefone.setText("");
        textPacienteEditarNascimento.setText("");
        textPacienteEditarCPF.setText("");
        textPacienteEditarEndereco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultaAdicionarVoltar;
    private javax.swing.JButton btPacienteEditar;
    private javax.swing.JButton btPacienteEditarVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textPacienteEditarCPF;
    private javax.swing.JTextField textPacienteEditarEndereco;
    private javax.swing.JTextField textPacienteEditarNascimento;
    private javax.swing.JTextField textPacienteEditarNome;
    private javax.swing.JTextField textPacienteEditarTelefone;
    // End of variables declaration//GEN-END:variables
}
